# Generated by Django 4.0.4 on 2023-02-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armap', '0002_alter_building_back_view_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='back_view_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='back_view_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='front_view_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='front_view_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='left_view_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='left_view_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='right_view_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='right_view_long',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
