# Generated by Django 4.0.4 on 2023-02-27 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armap', '0003_alter_building_back_view_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_coords',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='armap.route'),
            preserve_default=False,
        ),
    ]
